export const ERROR_CODE = {
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  BAD_REQUEST: 'BAD_REQUEST',
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  NOT_FOUND: 'NOT_FOUND',
  CONFLICT: 'CONFLICT',
  TOO_MANY_REQUESTS: 'TOO_MANY_REQUESTS',
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',

  AUTH_EMAIL_ALREADY_REGISTERED: 'AUTH_EMAIL_ALREADY_REGISTERED',
  AUTH_INVALID_CREDENTIALS: 'AUTH_INVALID_CREDENTIALS',
  AUTH_UNAUTHORIZED: 'AUTH_UNAUTHORIZED',
  AUTH_SESSION_INVALID: 'AUTH_SESSION_INVALID',
  AUTH_ACCOUNT_DISABLED: 'AUTH_ACCOUNT_DISABLED',
  AUTH_CURRENT_PASSWORD_REQUIRED: 'AUTH_CURRENT_PASSWORD_REQUIRED',
  AUTH_CURRENT_PASSWORD_INVALID: 'AUTH_CURRENT_PASSWORD_INVALID',
  AUTH_OAUTH_STATE_INVALID: 'AUTH_OAUTH_STATE_INVALID',
  AUTH_OAUTH_GOOGLE_EXCHANGE_FAILED: 'AUTH_OAUTH_GOOGLE_EXCHANGE_FAILED',
  AUTH_OAUTH_GOOGLE_PROFILE_FAILED: 'AUTH_OAUTH_GOOGLE_PROFILE_FAILED',
  AUTH_OAUTH_GOOGLE_EMAIL_REQUIRED: 'AUTH_OAUTH_GOOGLE_EMAIL_REQUIRED',
  AUTH_OAUTH_GOOGLE_ACCESS_DENIED: 'AUTH_OAUTH_GOOGLE_ACCESS_DENIED',

  VAULT_ITEM_NOT_FOUND: 'VAULT_ITEM_NOT_FOUND',
  VAULT_DECRYPTION_FAILED: 'VAULT_DECRYPTION_FAILED',
} as const;

export type ErrorCode = (typeof ERROR_CODE)[keyof typeof ERROR_CODE];
